### PR TITLE
Implemented Simple product card template

### PR DESCRIPTION
**Pull request by freddychenyouren2**
This is for issue #13 

## Changes made
- Created a simple Product Card template with MUI as a separate component in `product-card.tsx`
- Added a placeholder image temporarily. Eventually, the image should only be used if there is no available image for that product.
- Added a simple Welcome Message when users first access the page.

### CODE REVIEW

**Review by nknguyenhc — CHANGES_REQUESTED** [review]
image

Currently the product image is cutoff. Is it possible to:

1. Increase the height of the image frame.
2. Fit the image in the frame, so that image is always shown in full. You may want to test out with a horizontally long image as well.

**Comment by freddychenyouren2** [comment]
After commit #[9023027](https://github.com/nknguyenhc/luminous-zephyr/pull/15/commits/90230275d4a29754054bb281914921d13dbc9cf9), The product page may look like the following image if there are horizontally and vertically long images:

image

Images are now strictly contained within the CardMedia container. Padding does not seem to be appropriate as it did not appear visually appealing.

**Comment by nknguyenhc** [comment]
@freddychenyouren2 I think your screenshot is on mobile? It looks fine, but on desktop each card looks quite long.

image

**Comment by freddychenyouren2** [comment]
Modified accordingly in #[789ee7c](https://github.com/nknguyenhc/luminous-zephyr/pull/15/commits/789ee7c47772aee72631f799bc26de06d1dbd226) to introduce more responsive design:

- In large screens like Laptop/PC, there will be 4 Product Cards per row.
- In smaller screens like Mobile Phones, there will be 2 Product Cards per row.

**Review by nknguyenhc — APPROVED** [review]
LGTM!

**Pull request merged**
